  version: '2'
  services:
      loadbalance:
          image: httpd:latest
          ports: 
            - "81:80"
          volumes:
            - /home/vagrant/dockerc/conf/:/usr/local/apache2/conf
            - /home/vagrant/dockerc/htdocs/:/usr/local/apache2/htdocs

      node1:
        image: httpd:latest
        ports:
          - "82:80"
        volumes:
         - /home/vagrant/dockera/apache2/htdocs/:/usr/local/apache2/htdocs

      node2:
        image: httpd:latest
        ports:
          - "83:80"
        volumes:
          - /home/vagrant/dockerb/apache2/htdocs/:/usr/local/apache2/htdocs

      node3:
        image: httpd:latest
        ports:
          - "84:80"
        volumes:
          - /home/vagrant/dockerd/apache2/conf/:/usr/local/apache2/conf
          - /home/vagrant/dockerd/apache2/htdocs/:/usr/local/apache2/htdocs