Vagrant.configure(2) do |config| 
  
     config.vm.define "ubuntut" do |ubuntut|
	     
		 ubuntut.vm.box = "ubuntu/trusty64"
		 
		 ubuntut.vm.provision :shell, path: "LxdeVagrant.sh"

		 ubuntut.vm.provider "virtualbox" do |v|
             v.name = "ubuntut"
		     v.memory = 4096
		     v.cpus = 2 
			 v.customize ["modifyvm", :ubuntut, "--vram", "64"]
			 v.gui = true
	     end		
     end
end