    version: '2'
    services:
        jenkinsm:
             build: .
             ports:
                - "8600:8080"
             volumes:
                - /home/vagrant/data/:/usr/local/data
             depends_on:
                - jenkinss1
                
        jenkinss1:
             build: ./slavedock
             volumes:
                - /home/vagrant/data/:/usr/local/data